const API = (window.SJ_ADMIN_API || '').replace(/\/$/, '');
const state = { token: sessionStorage.getItem('sj_admin_token') || '', workbook: null, file: null };
const categories = ['ANIME','KDRAMA','MOVIES','VIVAMAX','PINOY MOVIE','DISNEY','KWENTONG PAMBATA','CARTOON','MARVEL','MOVIES [ENGLISH]','PC GAMES','ANDROID GAMES','PC SOFTWARE'];
const $ = (id) => document.getElementById(id);
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent=name[0].toUpperCase()+name.slice(1);$('sidebar').classList.remove('open');location.hash=name}
document.querySelectorAll('[data-view], [data-view-jump]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view||btn.dataset.viewJump)));
$('menuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
showView(location.hash.slice(1)||'overview');
const choices=$('categoryChoices');categories.forEach(name=>{const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${name}"><span>${name}</span>`;choices.append(label)});
$('fullAccess').addEventListener('change',e=>choices.querySelectorAll('input').forEach(input=>{input.disabled=e.target.checked;input.checked=false}));
function updatePinPreview(){const pin=$('pinInputAdmin').value.replace(/\D/g,'').slice(0,4);$('pinInputAdmin').value=pin;$('pinMessagePreview').textContent=`Your access PIN is ${pin||'••••'}.`}
$('pinInputAdmin').addEventListener('input',updatePinPreview);
$('copyPinMessage').addEventListener('click',async()=>{await navigator.clipboard.writeText($('pinMessagePreview').textContent);toast('Customer message copied.')});
async function api(path,options={}){if(!API)throw new Error('Secure admin service is not connected yet.');const headers={...(options.headers||{})};if(state.token)headers.authorization=`Bearer ${state.token}`;const res=await fetch(`${API}${path}`,{...options,headers});if(!res.ok)throw new Error((await res.json().catch(()=>({}))).error||`Request failed (${res.status})`);return res}
async function checkConnection(){if(!API){$('setupBanner').hidden=false;$('connectionLabel').textContent='Secure service not connected';return}try{await api('/api/health');$('connectionLabel').textContent='Secure service connected';document.querySelector('.status-dot').style.background='#34d399';$('setupBanner').hidden=!state.token}catch{$('setupBanner').hidden=false;$('connectionLabel').textContent='Connection needs attention'}}
checkConnection();
$('downloadExcel').addEventListener('click',async()=>{try{const res=await api('/api/database');const blob=await res.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DATABASE_SERVER.xlsx';a.click();URL.revokeObjectURL(a.href)}catch(e){toast(e.message)}});
$('excelUpload').addEventListener('change',async e=>{const file=e.target.files[0];state.file=file||null;$('fileLabel').textContent=file?file.name:'Tap to choose an Excel file';$('validationBadge').textContent=file?'Ready to validate':'No file selected';$('validationChecks').innerHTML=file?`<p><b>${file.name}</b> selected (${(file.size/1024/1024).toFixed(2)} MB).</p><p>The secure validator will check sheets, headers, IDs, PINs, and deletions before publishing.</p>`:'<p>Choose an Excel file.</p>';$('publishExcel').disabled=!file});
$('publishExcel').addEventListener('click',async()=>{if(!state.file)return;try{const body=new FormData();body.append('database',state.file);$('publishExcel').disabled=true;$('publishExcel').textContent='Validating and publishing…';const res=await api('/api/publish',{method:'POST',body});const result=await res.json();toast(result.message||'Website update started successfully.')}catch(e){toast(e.message)}finally{$('publishExcel').disabled=false;$('publishExcel').textContent='Publish Website Update'}});
$('pinForm').addEventListener('submit',async e=>{e.preventDefault();const pin=$('pinInputAdmin').value;if(!/^\d{4}$/.test(pin))return toast('Please enter exactly 4 digits.');const selected=$('fullAccess').checked?['FULL']:[...choices.querySelectorAll('input:checked')].map(x=>x.value);if(!selected.length)return toast('Choose FULL or at least one category.');try{await api('/api/pins',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin,categories:selected,note:$('pinNote').value})});toast('PIN added. Website publishing started.');e.target.reset();choices.querySelectorAll('input').forEach(x=>x.disabled=false);updatePinPreview()}catch(err){toast(err.message)}});
